# Generated by Django 2.0.7 on 2018-07-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180701_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pages/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pages.Page')),
            ],
            options={
                'ordering': ('file',),
            },
        ),
    ]
