# Generated by Django 2.0.6 on 2018-07-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Used in the URL', max_length=100)),
                ('code', models.TextField()),
                ('svg', models.TextField()),
                ('kind', models.CharField(choices=[('drawing', 'drawing'), ('animation', 'animation'), ('unlisted', 'unlisted')], max_length=15)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('slug', 'name')},
        ),
    ]
