# Generated by Django 2.1b1 on 2018-07-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0002_creation_historicalcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcreation',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
