# Generated by Django 2.1b1 on 2018-07-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0003_auto_20180711_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.AlterModelOptions(
            name='creation',
            options={'ordering': ('-pk',)},
        ),
    ]
