# Generated by Django 2.1b1 on 2018-07-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0004_auto_20180711_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creations.Creation'),
        ),
        migrations.AddField(
            model_name='historicalcreation',
            name='base',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='creations.Creation'),
        ),
    ]
