# Generated by Django 2.1b1 on 2018-07-12 17:06

import autoslug.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creations', '0005_auto_20180712_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('author',)),
        ),
        migrations.AlterField(
            model_name='historicalcreation',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('author',)),
        ),
        migrations.AlterUniqueTogether(
            name='creation',
            unique_together={('slug', 'author')},
        ),
    ]
