# Generated by Django 2.1b1 on 2018-07-12 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0006_auto_20180712_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creation',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='creations.Creation'),
        ),
    ]
