# Generated by Django 2.1b1 on 2018-07-15 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creations', '0007_auto_20180712_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='loving',
            field=models.ManyToManyField(blank=True, related_name='loved', to=settings.AUTH_USER_MODEL),
        ),
    ]
