# Generated by Django 2.1b1 on 2018-07-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0008_creation_loving'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcreation',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
    ]
