# Generated by Django 2.1.4 on 2018-12-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0009_auto_20180730_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcreation',
            name='base',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='creations.HistoricalCreation'),
        ),
    ]
