# Generated by Django 4.2.30 on 2026-05-12 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0010_auto_20181229_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcreation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical creation', 'verbose_name_plural': 'historical creations'},
        ),
        migrations.AlterField(
            model_name='historicalcreation',
            name='base',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='creations.creation'),
        ),
        migrations.AlterField(
            model_name='historicalcreation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
