# Generated by Django 4.2.30 on 2026-05-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creations', '0011_alter_historicalcreation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalcreation',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
    ]
