"""
Django settings for shrew project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

import environ

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Read from the environment
env = environ.Env()
env.read_env(os.path.join(BASE_DIR, '..', '.env'))

SITE_ID = 1

# SECURITY WARNING: keep the secret key used in production secret!
# A default is provided so tests and ``manage.py`` introspection commands
# work without a .env file. ``prod.py`` overrides this with a hard
# requirement so a misconfigured deploy fails loudly rather than silently
# falling back to an insecure key.
SECRET_KEY = env('DJANGO_SECRET_KEY', default='insecure-default-secret-key-do-not-use-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',

    'compressor',
    'compressor_toolkit',
    'django_markwhat',
    'adminsortable2',
    'micawber.contrib.mcdjango',
    'widget_tweaks',
    'bulma',
    'simple_history',
    'rest_framework',
    'captcha',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',

    'shrew.apps.creations',
    'shrew.apps.pages',
    'shrew.apps.teachers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'shrew.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shrew.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DJANGO_DATABASE_URL', default='sqlite:///db.sqlite3'),
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_FORMS = {
    'signup': 'shrew.apps.users.forms.ShrewSignupForm',
}
SOCIALACCOUNT_FORMS = {
    'signup': 'shrew.apps.users.forms.ShrewSocialSignupForm',
}
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_USERNAME_VALIDATORS = 'shrew.apps.users.validators.username_validators'
LOGIN_REDIRECT_URL = '/'



# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# New ``startproject`` boilerplate includes this, but Django keeps the
# pre-3.2 default of ``AutoField`` for projects that never set it (with a
# W042 warning) to preserve existing schemas. We opt in explicitly; the
# 0012/0006 migrations widen the existing PK/FK columns accordingly.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
MEDIA_URL = '/media/'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

# Django Compressor
#
# We use Dart Sass (``sass`` npm package) instead of the deprecated
# ``node-sass``; ``shrew.precompilers.DartSCSSCompiler`` adapts the SCSS
# compiler flags accordingly.
COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'shrew.precompilers.DartSCSSCompiler'),
    ('module', 'compressor_toolkit.precompilers.ES6Compiler'),
    ('skulpt-module', 'shrew.precompilers.SkulptModuleFilter'),
    ('skulpt-module-es6', 'shrew.precompilers.SkulptModuleES6Filter'),
)

# Override the SCSS compiler command template:
#  - Dart Sass takes the output path as a positional argument and uses
#    ``--style=expanded`` instead of ``--output-style expanded``.
#  - postcss-cli 5 resolves plugin modules from ``node_modules`` automatically,
#    so we pass the bare package name (``autoprefixer``) rather than a path.
COMPRESS_SCSS_COMPILER_CMD = (
    '{node_sass_bin} --style=expanded {paths} "{infile}" "{outfile}" && '
    '{postcss_bin} --use autoprefixer '
    '--autoprefixer.browsers "{autoprefixer_browsers}" -r "{outfile}"'
)

CLOUDCONVERT_KEY = env.str("DJANGO_CLOUDCONVERT_KEY", default="")

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_caches',
    }
}

# django-recaptcha ships built-in test keys that always validate as a fallback
# when no real key is configured (it emits a system check warning that we
# silence in test settings).
RECAPTCHA_PUBLIC_KEY = env.str("DJANGO_RECAPTCHA_PUBLIC_KEY", default="")
RECAPTCHA_PRIVATE_KEY = env.str("DJANGO_RECAPTCHA_PRIVATE_KEY", default="")
