from .base import *  # noqa

DEBUG = False
ALLOWED_HOSTS = ['shrew.app']

# Security
SECURE_SSL_REDIRECT = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365 * 5  # 5 years

STATIC_ROOT = env.str("DJANGO_STATIC_ROOT")
MEDIA_ROOT = env.str("DJANGO_MEDIA_ROOT")
COMPRESS_OFFLINE = True

ADMINS = [
    ('Ludwik', 'ludwik@gmail.com'),
]
MANAGERS = ADMINS

# Email
DEFAULT_FROM_EMAIL = SERVER_EMAIL = 'noreply@shrew.app'
EMAIL_SUBJECT_PREFIX = '[Code Shrew] '
EMAIL_HOST = env('DJANGO_EMAIL_HOST')
EMAIL_HOST_USER = env('DJANGO_EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('DJANGO_EMAIL_HOST_PASSWORD')
EMAIL_PORT = 465
EMAIL_USE_SSL = True
